install ansible
install arp-scan
install autojump
install automake
install osx-cross/avr/avr-gcc
install avrdude
install awscli
install bat
install bfg
install chromedriver
install koekeishiya/formulae/chunkwm
install cmake
install cpulimit
install dfu-programmer
install docutils
install elasticsearch
install d12frosted/emacs-plus/emacs-plus
install exercism
install ffmpeg
install fontforge
install fzf
install px4/px4/gcc-arm-none-eabi
install gifsicle
install git
install git-duet/tap/git-duet
install git-lfs
install global
install gnu-sed
install go
install gobject-introspection
install grc
install grv
install handbrake
install heroku/brew/heroku
install htop
install hub
install iftop
install imagemagick
install iperf3
install ispell
install jemalloc
install libav
install libidn
install libxml2
install lmdb
install logrotate
install lua-nginx-module
install lua@5.1
install memcached
install mkvtoolnix
install mosh
install mp4v2
install mysql
install mysql-client
install mysql@5.7
install nasm
install neovim
install ngx-devel-kit
install nmap
install node@10
install notmuch
install open-mpi
install passenger
install postgresql
install postgresql@10
install push-stream-nginx-module
install rabbitmq
install rbenv
install reattach-to-user-namespace
install redis
install rename
install ripgrep
install shpotify
install koekeishiya/formulae/skhd
install sox
install speedtest-cli
install ssh-copy-id
install texi2html
install texinfo
install the_silver_searcher
install tmate
install tmux
install tokyo-cabinet
install universal-ctags/universal-ctags/universal-ctags
install vim
install watchman
install wget
install yarn
install zsh
