#!/bin/sh

#
# Brew packages
#
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install brew-cask
brew install git
brew install node
brew install nvm
brew install sqlite
brew install ssh-copy-id
brew install tmux
brew install wget
brew install ansible
brew install ctags
brew install imagemagick
brew install openssl
brew install rcm
brew install reattach-to-user-namespace
brew install vim
brew install redis
brew install mysql
brew install postgres
brew install the_silver_searcher
brew install htop
brew install heroku
brew install heroku-toolbelt
brew install zsh
brew install yarn
brew install wget
brew install libyaml
brew install fzf
brew install rbenv

#
# Cask packages
#
brew cask install angry-ip-scanner
brew cask install firefox
brew cask install google-chrome
brew cask install iterm2
brew cask install openemu
brew cask install tableplus
brew cask install sequel-pro
brew cask install sqlpro-for-sqlite
brew cask install slack
brew cask install spotify
brew cask install virtualbox
brew cask install ipassword
brew cask install postico
brew cask install docker
