#!/bin/bash

# -e exit with any non-zero status
# -u treat unset vars as an error when substituting
set -eu

RED="\033[0;31m"
GREEN="\033[0;32m"
BLUE="\033[0;34m"
ENDCOLOR="\033[0m"

function msg() {
	echo -e "$1"
}

function info() {
	msg "$BLUE$1$ENDCOLOR"
}

function success() {
	msg "${GREEN}$1${ENDCOLOR}"
}

function error() {
	msg "${RED}$1${ENDCOLOR}"
}

info "Mac setup - enter your password to get started:"
sudo echo "Let's go!"

if [ ! "$(command -v brew)" ]; then
	info "Installing homebrew..."
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi
success "Homebrew is g2g"

info "Install Homebrew packages:"
brew bundle --file "$HOME/dotfiles/Brewfile"

if [ ! -d "$HOME/dotfiles" ]; then
	info "Cloning dotfiles..."
	git clone git@github.com:bweave/dotfiles.git "$HOME/dotfiles"
fi
success "dotfiles cloned"

info "Symlinking dotfiles..."
stow --dir "$HOME/dotfiles" --target "$HOME"
success "dotfiles are g2g"

info "Creating .secrets..."
touch "$HOME/.secrets"

info "Installing neovim..."
"$HOME/dotfiles/install-neovim-nightly.sh"

sudo defaults write -g InitialKeyRepeat -int 10 # normal minimum is 15 (225 ms)
sudo defaults write -g KeyRepeat -int 1         # normal minimum is 2 (30 ms)
success "fast key repeat set"

rubies="$(rbenv versions --bare)"
ruby_version=$(echo "$rubies" | fzf --prompt="Select Ruby version: ")
info "Installing ruby v$ruby_version..."
rbenv install -s "$ruby_version"
rbenv global "$ruby_version"
eval "$(rbenv init - bash)"
gem install bundler rails
rbenv rehash
success "Ruby $ruby_version installed"

info "setting up NVM with Node LTS"
mkdir -p "$HOME/.nvm"
nvm install --lts
nvm alias system node
npm i -g \
	vscode-langservers-extracted \
	bash-language-server
success "NVM and Node are g2g"

echo
success =================================================
success "Donezo!"
success =================================================
echo
