#!/bin/bash

# https://gist.github.com/lukasnellen/c332f207cde666e0dfa5938d8dd0c161
# Fix SSH auth socket location so agent forwarding works with tmux
if [ ! -S $HOME/.ssh/ssh_auth_sock -a -S "$SSH_AUTH_SOCK" ]; then
  ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi
